rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode

branches:
  only:
    - develop
    - master

#after_script:
#  - "ruby ./benchmark/compare_mem_w_buf.rb"

notifications:
  email:
    - chris@dinarrr.com
