# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "io_shuten"
  s.version = "0.0.1.dev0"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Grabo"]
  s.date = "2012-01-21"
  s.description = "IO::shuten \u{2013} Use databases as IO handler like you would do with files and streamgem."
  s.email = ["chris@dinarrr.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.de",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    ".simplecov",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.de",
    "README.md",
    "Rakefile",
    "io_shuten.gemspec",
    "lib/io_shuten.rb",
    "lib/io_shuten/base.rb",
    "lib/io_shuten/mongo.rb",
    "lib/io_shuten/redis.rb",
    "lib/io_shuten/version.rb",
    "spec/externals/logger_spec.rb",
    "spec/lib/base_spec.rb",
    "spec/lib/mongo_spec.rb",
    "spec/lib/redis_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/asaaki/io_shuten"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "IO::shuten \u{2013} Use databases as IO handler."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hiredis>, ["~> 0.4.4"])
      s.add_runtime_dependency(%q<redis>, ["~> 2.2.2"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-csv>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<pry-doc>, [">= 0"])
    else
      s.add_dependency(%q<hiredis>, ["~> 0.4.4"])
      s.add_dependency(%q<redis>, ["~> 2.2.2"])
      s.add_dependency(%q<bson_ext>, ["~> 1.5.2"])
      s.add_dependency(%q<mongo>, ["~> 1.5.2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_dependency(%q<simplecov-csv>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<pry-doc>, [">= 0"])
    end
  else
    s.add_dependency(%q<hiredis>, ["~> 0.4.4"])
    s.add_dependency(%q<redis>, ["~> 2.2.2"])
    s.add_dependency(%q<bson_ext>, ["~> 1.5.2"])
    s.add_dependency(%q<mongo>, ["~> 1.5.2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    s.add_dependency(%q<simplecov-csv>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<pry-doc>, [">= 0"])
  end
end

